# Generated by Django 5.1.6 on 2025-03-03 18:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finoperation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="finoperation",
            name="last_execution",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finoperation",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="goalbudget",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="TransferBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "from_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_out_set",
                        to="financew.budget",
                    ),
                ),
                (
                    "to_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_in_set",
                        to="financew.budget",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferGoalBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "from_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financew.budget",
                    ),
                ),
                (
                    "to_goalbudget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financew.goalbudget",
                    ),
                ),
            ],
        ),
    ]
