# Generated by Django 5.1.6 on 2025-02-19 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_amount",
                    models.DecimalField(decimal_places=2, max_digits=19),
                ),
                (
                    "fin_operation_type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                        max_length=7,
                    ),
                ),
                ("fin_operation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financew.budget",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "finoperations",
            },
        ),
    ]
