# Generated by Django 5.1.6 on 2025-02-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalbudget",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
