# Generated by Django 5.1.6 on 2025-02-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0002_finoperation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"verbose_name_plural": "budgets"},
        ),
        migrations.RenameField(
            model_name="finoperation",
            old_name="operation_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="finoperation",
            old_name="fin_operation_date",
            new_name="date_added",
        ),
        migrations.RenameField(
            model_name="finoperation",
            old_name="fin_operation_type",
            new_name="type",
        ),
    ]
