# Generated by Django 5.1.6 on 2025-02-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0002_finoperation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"verbose_name_plural": "budgets"},
        ),
    ]
