# Generated by Django 5.1.6 on 2025-02-28 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0002_alter_goalbudget_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "owner"), name="unique_category_for_user"
            ),
        ),
    ]
