# Generated by Django 5.1.6 on 2025-03-01 15:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0004_remove_category_unique_category_for_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "from_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_out_set",
                        to="financew.budget",
                    ),
                ),
                (
                    "to_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_in_set",
                        to="financew.budget",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "transfers",
            },
        ),
        migrations.CreateModel(
            name="TransferGoalBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "from_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financew.budget",
                    ),
                ),
                (
                    "to_goalbudget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financew.goalbudget",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "transfers",
            },
        ),
    ]
