# Generated by Django 5.1.6 on 2025-02-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0004_category_budget_currency_budget_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
