# Generated by Django 5.1.6 on 2025-03-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0005_transferbudget_transfergoalbudget"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transferbudget",
            options={},
        ),
        migrations.AlterModelOptions(
            name="transfergoalbudget",
            options={},
        ),
    ]
