# Generated by Django 5.1.6 on 2025-02-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0005_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finoperation",
            name="type",
            field=models.CharField(
                choices=[("income", "Прибуток"), ("expense", "Витрати")], max_length=7
            ),
        ),
    ]
