# Generated by Django 5.0.6 on 2025-02-23 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financew', '0006_alter_finoperation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finoperation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financew.category'),
        ),
    ]
