# Generated by Django 5.1.6 on 2025-02-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financew', '0003_alter_budget_options'),
        ('financew', '0006_alter_finoperation_type'),
    ]

    operations = [
    ]
