# Generated by Django 5.1.6 on 2025-02-21 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0007_merge_20250221_1350"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finoperation",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financew.category",
            ),
        ),
    ]
