# Generated by Django 5.1.6 on 2025-02-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0007_alter_finoperation_category"),
        ("financew", "0007_merge_20250220_1812"),
        ("financew", "0008_alter_finoperation_category"),
    ]

    operations = []
