# Generated by Django 5.1.6 on 2025-02-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0010_budget_owner_category_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalBudget",
            fields=[
                (
                    "budget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="financew.budget",
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                "verbose_name_plural": "budgets",
            },
            bases=("financew.budget",),
        ),
    ]
