# Generated by Django 5.1.6 on 2025-02-27 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financew", "0010_budget_owner_category_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="finoperation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="finoperation",
            name="last_execution",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finoperation",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
